"""Deterministic scenario catalog for synthetic enterprise traces."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ScenarioSpec:
    """Input specification for one synthetic trace generation request."""

    scenario_id: str
    domain: str
    task_family: str
    title: str
    objective: str
    context_brief: str
    required_operations: tuple[str, ...]
    required_candidate_kinds: tuple[str, ...]
    risk_level: str


_DOMAIN_SCENARIOS: dict[
    str,
    list[tuple[str, str, str, str, tuple[str, ...], tuple[str, ...], str]],
] = {
    "loan_contract": [
        (
            "key_terms",
            "借款合同关键条款提取",
            "从合同中提取额度、期限、利率、还款方式和用途限制，并验证字段完整性。",
            "一份虚构中小企业流动资金借款合同，包含固定利率、按月付息、到期还本和用途限制。",
            ("document_parse", "clause_extract", "field_normalize", "contract_validate"),
            ("EXTRACTOR", "ADAPTER", "VALIDATOR", "FSM"),
            "medium",
        ),
        (
            "repayment_schedule",
            "还款计划生成与核对",
            "根据本金、年利率、期限和计息规则生成计划，并核对总额与日期。",
            "一份虚构等额本息贷款合同，包含节假日顺延和首期不足月计息规则。",
            ("term_extract", "schedule_calculate", "date_adjust", "amount_validate"),
            ("TOOL", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "covenant_monitoring",
            "财务约束条款监测",
            "识别资产负债率和流动比率约束，并判断虚构报告是否触发预警。",
            "合同约定两个财务指标阈值，另附同一虚构借款人的季度财务摘要。",
            ("covenant_extract", "metric_map", "threshold_evaluate", "alert_build"),
            ("EXTRACTOR", "ADAPTER", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "collateral_check",
            "抵押物资料完整性检查",
            "根据合同约定检查抵押物清单、估值、权属证明和保险资料。",
            "虚构设备抵押贷款资料包，部分附件存在日期过期或编号不一致。",
            ("requirement_extract", "document_match", "expiry_check", "gap_report"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "guarantee_liability",
            "保证责任范围识别",
            "区分一般保证与连带责任保证，提取责任范围和保证期间。",
            "一份完全虚构的保证合同，正文与补充条款存在需要按优先级解释的描述。",
            ("clause_classify", "priority_resolve", "liability_extract", "legal_flag"),
            ("EXTRACTOR", "POLICY", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "prepayment_fee",
            "提前还款费用测算",
            "识别提前还款条件并根据虚构申请日期计算违约金。",
            "合同规定分期限的提前还款费率，客户提供了部分还款金额和申请日期。",
            ("condition_extract", "period_classify", "fee_calculate", "result_validate"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "default_remedy",
            "违约事件与救济路径识别",
            "将逾期、用途违规和交叉违约映射到合同中的通知与补救路径。",
            "虚构合同及三条事件记录，要求只形成风险提示，不执行真实催收或冻结。",
            ("event_classify", "clause_match", "remedy_route", "human_escalate"),
            ("FSM", "POLICY", "VALIDATOR", "SKELETON"),
            "high",
        ),
        (
            "version_compare",
            "合同版本差异核对",
            "比较两个虚构版本并识别利率、担保、通知期限和争议解决条款变化。",
            "同一合同的草案版和签署版，含编号变化、文字调整和四处实质差异。",
            ("document_align", "clause_diff", "materiality_classify", "diff_validate"),
            ("TOOL", "ADAPTER", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "rate_adjustment",
            "浮动利率调整核算",
            "依据重定价日、基准变化和加点规则生成新的执行利率。",
            "虚构合同使用年度重定价规则，附两期基准利率和一个非工作日重定价日。",
            ("rule_extract", "rate_lookup", "date_adjust", "rate_calculate"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "drawdown_eligibility",
            "贷款提款条件检查",
            "按合同先决条件检查提款申请，并输出通过项、缺失项和人工复核项。",
            "虚构授信合同列出六项提款条件，申请资料中有四项满足、一项缺失、一项含糊。",
            ("condition_extract", "evidence_match", "gap_classify", "decision_package"),
            ("EXTRACTOR", "FSM", "VALIDATOR", "SKELETON"),
            "high",
        ),
    ],
    "financial_report": [
        (
            "balance_sheet_reconcile",
            "资产负债表勾稽校验",
            "校验资产、负债和所有者权益的勾稽关系并定位差额。",
            "一份虚构季度资产负债表，设置一个可解释的汇总差额和一个字段映射问题。",
            ("table_parse", "field_map", "equation_check", "variance_report"),
            ("EXTRACTOR", "ADAPTER", "TOOL", "VALIDATOR"),
            "medium",
        ),
        (
            "income_yoy",
            "利润表同比分析",
            "计算收入、毛利和净利润同比变化并给出证据化摘要。",
            "虚构企业连续两年同季度利润表，包含一次性收益和口径调整说明。",
            ("table_extract", "period_align", "ratio_calculate", "summary_build"),
            ("EXTRACTOR", "ADAPTER", "TOOL", "FSM"),
            "medium",
        ),
        (
            "cashflow_anomaly",
            "现金流异常识别",
            "识别经营现金流与利润背离、异常大额流出和分类不一致。",
            "虚构现金流量表及三笔重大交易摘要，所有金额和主体均为合成数据。",
            ("cashflow_extract", "trend_compare", "anomaly_score", "evidence_validate"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "financial_ratios",
            "核心财务比率计算",
            "计算流动比率、速动比率、资产负债率和净资产收益率并验证公式。",
            "虚构财务报表字段齐全，但存货和平均净资产需要按规则推导。",
            ("metric_extract", "formula_select", "ratio_calculate", "formula_validate"),
            ("ADAPTER", "TOOL", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "audit_notes",
            "审计附注事项提取",
            "从附注提取保留事项、持续经营风险、关联交易和或有负债。",
            "虚构审计报告附注，包含明确事项、否定表述和需要人工判断的模糊段落。",
            ("section_locate", "fact_extract", "negation_handle", "review_route"),
            ("EXTRACTOR", "FSM", "VALIDATOR", "HUMAN"),
            "high",
        ),
        (
            "segment_performance",
            "分部经营表现分析",
            "统一不同分部口径并比较收入、利润率和增长贡献。",
            "虚构集团的三个业务分部采用不同币种和内部交易抵销口径。",
            ("segment_extract", "currency_adapt", "elimination_apply", "ranking_build"),
            ("EXTRACTOR", "ADAPTER", "TOOL", "FSM"),
            "medium",
        ),
        (
            "budget_variance",
            "预算执行偏差分析",
            "将实际与预算对齐，计算偏差并按阈值分级。",
            "虚构部门月度预算与实际表，含科目更名和一笔跨期费用。",
            ("account_map", "period_adjust", "variance_calculate", "threshold_route"),
            ("ADAPTER", "TOOL", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "receivable_aging",
            "应收账款账龄分析",
            "将发票归入账龄桶，计算逾期比例并识别集中度风险。",
            "虚构发票清单，包含贷项通知、部分回款和同一客户多个名称。",
            ("invoice_normalize", "payment_apply", "aging_bucket", "concentration_check"),
            ("ADAPTER", "TOOL", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "expense_classification",
            "费用科目分类复核",
            "依据会计科目规则重新分类费用并标注不确定项。",
            "虚构费用明细含差旅、软件订阅、资本化设备和混合用途支出。",
            ("description_extract", "rule_classify", "confidence_gate", "review_queue"),
            ("EXTRACTOR", "POLICY", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "management_summary",
            "管理层财务摘要生成",
            "基于已验证指标生成简短管理摘要并保留证据引用。",
            "虚构月度财务包，含预算、实际、现金和应收四组已核验数据。",
            ("verified_metric_load", "materiality_select", "summary_compose", "citation_check"),
            ("TOOL", "FSM", "VALIDATOR", "SKELETON"),
            "medium",
        ),
    ],
    "customer_service": [
        (
            "repayment_inquiry",
            "还款金额与日期咨询",
            "识别客户问题，核验身份状态并基于虚构账单回答下期还款信息。",
            "合成客服对话和脱敏账单摘要，不包含真实身份或账户数据。",
            ("intent_classify", "identity_gate", "bill_lookup", "response_validate"),
            ("FSM", "TOOL", "POLICY", "VALIDATOR"),
            "medium",
        ),
        (
            "overdue_complaint",
            "逾期费用投诉处理",
            "提取争议点、核对费用规则、生成解释并在需要时升级人工。",
            "虚构客户认为逾期费计算错误，对话中提供了缴款时间和渠道。",
            ("complaint_extract", "fee_rule_lookup", "timeline_compare", "escalation_route"),
            ("EXTRACTOR", "TOOL", "FSM", "HUMAN"),
            "high",
        ),
        (
            "rate_explanation",
            "贷款利率解释",
            "把合同利率组成转换为客户可理解的说明，并检查合规披露。",
            "合成客服对话涉及基准利率、加点和重定价，但不提供投资或法律建议。",
            ("question_normalize", "term_lookup", "explanation_build", "disclosure_validate"),
            ("ADAPTER", "FSM", "POLICY", "VALIDATOR"),
            "medium",
        ),
        (
            "prepayment_request",
            "提前还款申请受理",
            "收集必要信息、检查缺口、生成申请单并明确后续人工审批。",
            "虚构对话中客户只提供部分还款日期和金额，禁止直接承诺审批结果。",
            ("intent_classify", "field_collect", "gap_check", "application_create"),
            ("FSM", "EXTRACTOR", "TOOL", "VALIDATOR"),
            "high",
        ),
        (
            "fraud_report",
            "疑似欺诈报告分流",
            "识别高风险信号，最小化收集信息并立即路由人工安全团队。",
            "合成客户报告陌生扣款，流程不得要求密码、验证码或完整卡号。",
            ("risk_signal_detect", "sensitive_data_guard", "case_create", "urgent_route"),
            ("FSM", "POLICY", "TOOL", "HUMAN"),
            "high",
        ),
        (
            "payment_failure",
            "还款失败排障",
            "根据错误码和时间线定位常见原因，给出只读排障步骤。",
            "虚构客服对话和支付错误码，不允许代理重复发起真实扣款。",
            ("error_extract", "code_lookup", "troubleshooting_route", "resolution_validate"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "profile_correction",
            "客户资料更正请求",
            "识别更正字段，执行身份与材料检查，生成待人工处理工单。",
            "合成对话要求更正联系地址，示例信息完全虚构并已脱敏。",
            ("field_extract", "identity_gate", "document_check", "ticket_create"),
            ("EXTRACTOR", "POLICY", "FSM", "TOOL"),
            "high",
        ),
        (
            "credit_dispute",
            "征信信息异议受理",
            "提取异议对象和证据，检查完整性并生成合规时限提醒。",
            "虚构客户对一条贷款状态提出异议，代理只能受理不能自行修改记录。",
            ("dispute_extract", "evidence_check", "case_create", "deadline_schedule"),
            ("EXTRACTOR", "FSM", "TOOL", "POLICY"),
            "high",
        ),
        (
            "complaint_routing",
            "综合服务投诉路由",
            "按产品、问题、严重度和情绪信号分类并路由合适队列。",
            "合成多轮对话同时涉及服务态度和账单疑问，需要拆成两个子问题。",
            ("conversation_segment", "issue_classify", "severity_score", "queue_route"),
            ("EXTRACTOR", "FSM", "TOOL", "VALIDATOR"),
            "medium",
        ),
        (
            "dialogue_quality",
            "客服对话质量与合规检查",
            "检查问候、身份验证、敏感信息、承诺用语和结束确认。",
            "一段虚构坐席对话，故意包含一个遗漏步骤和一句不当承诺。",
            ("turn_parse", "policy_check", "quality_score", "finding_report"),
            ("EXTRACTOR", "POLICY", "FSM", "VALIDATOR"),
            "high",
        ),
    ],
    "internal_communication": [
        (
            "action_items",
            "内部邮件行动项提取",
            "从邮件线程中提取负责人、任务、截止日期和依赖。",
            "虚构项目邮件包含回复引用、相对日期和一个未明确负责人事项。",
            ("thread_parse", "action_extract", "date_normalize", "gap_flag"),
            ("EXTRACTOR", "ADAPTER", "FSM", "VALIDATOR"),
            "low",
        ),
        (
            "policy_acknowledgement",
            "制度通知确认跟踪",
            "识别通知适用范围、确认期限并生成未确认名单。",
            "虚构信息安全制度通知和合成员工确认记录。",
            ("audience_extract", "deadline_extract", "receipt_match", "reminder_build"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "approval_routing",
            "邮件审批请求路由",
            "识别金额、事项和组织层级，将申请路由到正确审批链。",
            "虚构采购申请邮件，金额跨越两级阈值且缺少一份附件。",
            ("request_extract", "threshold_lookup", "attachment_check", "approval_route"),
            ("EXTRACTOR", "POLICY", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "deadline_reminder",
            "跨部门截止日期提醒",
            "统一邮件中的日期与时区，生成分级提醒但不真实发送。",
            "虚构跨地区项目通知含北京时间和伦敦时间，以及一个相对日期表达。",
            ("date_extract", "timezone_adapt", "priority_classify", "reminder_prepare"),
            ("EXTRACTOR", "ADAPTER", "FSM", "TOOL"),
            "low",
        ),
        (
            "confidentiality_classify",
            "内部信息密级分类",
            "依据内容和收件范围判断公开、内部、机密等级并给出处理约束。",
            "虚构邮件涉及未发布预算和普通会议安排，不包含真实商业秘密。",
            ("content_extract", "policy_classify", "recipient_scope_check", "handling_label"),
            ("EXTRACTOR", "POLICY", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "thread_consolidation",
            "冲突邮件信息合并",
            "按时间线合并多个回复，识别最新决定和仍未解决的冲突。",
            "虚构邮件线程中预算数字和交付日期经历两次更改。",
            ("thread_order", "fact_version", "conflict_detect", "current_state_build"),
            ("TOOL", "FSM", "VALIDATOR", "SKELETON"),
            "medium",
        ),
        (
            "meeting_decisions",
            "会议纪要转任务",
            "从会议通知和纪要中提取决定、行动项和复核点。",
            "虚构管理会议纪要含三个决定、四个行动项和一个待确认事项。",
            ("section_parse", "decision_extract", "task_build", "completeness_validate"),
            ("EXTRACTOR", "FSM", "TOOL", "VALIDATOR"),
            "low",
        ),
        (
            "org_announcement",
            "组织公告分发计划",
            "解析公告受众、渠道和生效时间，生成分发计划与确认点。",
            "虚构办公地点调整公告，涉及三个部门和远程员工。",
            ("audience_segment", "channel_select", "schedule_build", "coverage_validate"),
            ("FSM", "POLICY", "TOOL", "VALIDATOR"),
            "medium",
        ),
        (
            "incident_escalation",
            "内部事件通知升级",
            "识别事件严重度、信息缺口和通知对象，形成升级包。",
            "虚构系统可用性事件邮件，包含影响范围但缺少恢复时间。",
            ("incident_extract", "severity_classify", "gap_check", "escalation_package"),
            ("EXTRACTOR", "FSM", "POLICY", "HUMAN"),
            "high",
        ),
        (
            "compliance_receipt",
            "合规通知送达核验",
            "核对适用人员、发送记录、阅读确认和例外原因。",
            "虚构合规培训通知及合成送达回执，包含离职和休假例外。",
            ("population_load", "receipt_match", "exception_classify", "coverage_report"),
            ("TOOL", "FSM", "ADAPTER", "VALIDATOR"),
            "medium",
        ),
    ],
    "risk_compliance": [
        (
            "kyc_completeness",
            "KYC 资料完整性预检",
            "检查虚构企业客户资料的必填字段、有效期和受益所有人信息。",
            "完全合成的企业开户资料包，仅用于流程验证，不作真实准入决策。",
            ("requirement_load", "document_check", "expiry_validate", "gap_report"),
            ("TOOL", "FSM", "POLICY", "VALIDATOR"),
            "high",
        ),
        (
            "aml_alert_triage",
            "反洗钱告警初筛",
            "基于合成交易摘要整理告警证据并路由人工，不自动关闭告警。",
            "虚构交易模式包含频繁小额入账和集中转出，所有主体均为示例。",
            ("transaction_aggregate", "pattern_detect", "evidence_package", "human_route"),
            ("TOOL", "FSM", "POLICY", "HUMAN"),
            "high",
        ),
        (
            "sanctions_match",
            "制裁名单同名匹配复核",
            "对完全虚构名单进行标准化和相似匹配，并将不确定项交人工。",
            "合成客户名称与合成观察名单存在拼写近似，不涉及任何真实个人或实体。",
            ("name_normalize", "similarity_match", "threshold_gate", "human_route"),
            ("ADAPTER", "TOOL", "FSM", "HUMAN"),
            "high",
        ),
        (
            "retention_policy",
            "数据保留期限检查",
            "根据记录类别和虚构制度判断保留、归档或人工复核。",
            "合成文件清单涵盖合同、客服记录和普通通知，只输出建议不执行删除。",
            ("record_classify", "policy_lookup", "retention_calculate", "safe_report"),
            ("EXTRACTOR", "POLICY", "FSM", "VALIDATOR"),
            "high",
        ),
        (
            "access_request",
            "内部数据访问申请检查",
            "验证申请目的、最小权限、审批人和时限，输出允许或补充材料建议。",
            "虚构分析人员申请访问脱敏财务数据，范围部分超出岗位需要。",
            ("request_extract", "scope_compare", "policy_evaluate", "approval_route"),
            ("EXTRACTOR", "POLICY", "FSM", "VALIDATOR"),
            "high",
        ),
    ],
    "corporate_operations": [
        (
            "expense_reimbursement",
            "费用报销预审",
            "检查票据、金额、科目、出差申请和审批阈值。",
            "虚构差旅报销包含一张重复票据和一项超标准住宿费。",
            ("receipt_extract", "duplicate_check", "policy_evaluate", "review_route"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "medium",
        ),
        (
            "procurement_approval",
            "采购申请审批编排",
            "按金额、品类和供应商状态生成审批路径并检查附件。",
            "虚构软件采购申请超过部门阈值，供应商尽调尚未完成。",
            ("request_extract", "vendor_lookup", "threshold_route", "dependency_check"),
            ("EXTRACTOR", "TOOL", "FSM", "POLICY"),
            "medium",
        ),
        (
            "employee_onboarding",
            "员工入职任务编排",
            "根据岗位生成账号、设备、培训和资料任务，检查前置依赖。",
            "虚构新员工将从远程地点入职，不包含真实个人信息。",
            ("role_normalize", "checklist_select", "dependency_schedule", "completion_validate"),
            ("ADAPTER", "FSM", "TOOL", "VALIDATOR"),
            "medium",
        ),
        (
            "leave_workflow",
            "请假申请规则检查",
            "识别假期类型、日期和余额，确定审批路径与缺口。",
            "虚构员工提交跨月年假申请，包含一个法定节假日。",
            ("request_extract", "calendar_lookup", "balance_check", "approval_route"),
            ("EXTRACTOR", "TOOL", "FSM", "VALIDATOR"),
            "low",
        ),
        (
            "vendor_due_diligence",
            "供应商尽调资料预检",
            "核对企业资料、利益冲突声明、制裁筛查状态和风险问卷。",
            "完全合成的供应商资料包，存在一项过期证明和一项未回答问题。",
            ("requirement_load", "document_check", "risk_flag", "human_review_package"),
            ("TOOL", "FSM", "POLICY", "VALIDATOR"),
            "high",
        ),
    ],
}


def _build_catalog() -> tuple[ScenarioSpec, ...]:
    scenarios: list[ScenarioSpec] = []
    for domain, domain_items in _DOMAIN_SCENARIOS.items():
        for index, item in enumerate(domain_items, start=1):
            (
                task_family,
                title,
                objective,
                context_brief,
                operations,
                candidate_kinds,
                risk_level,
            ) = item
            scenarios.append(
                ScenarioSpec(
                    scenario_id=f"{domain}_{index:02d}_{task_family}",
                    domain=domain,
                    task_family=task_family,
                    title=title,
                    objective=objective,
                    context_brief=context_brief,
                    required_operations=operations,
                    required_candidate_kinds=candidate_kinds,
                    risk_level=risk_level,
                )
            )
    return tuple(scenarios)


SCENARIOS = _build_catalog()

